### PR TITLE
Self-host Asap typeface

### PR DESCRIPTION
**Pull request by agarzola**
This is a first stab at addressing #158. Using BrowserStack, I can’t see a difference in Chrome 60 running on Windows 10. Need some input from other folks reporting that issue. Please check out the Netlify preview and tell me if the problem persists.

cc: @StrangeWill @DigTK

### CODE REVIEW

**Comment by StrangeWill** [comment]
I don't see a difference either, still blocky.

**Comment by DigTK** [comment]
Same, see no difference.

**Comment by agarzola** [comment]
Ah, shit. This explains it: http://caniuse.com/#feat=svg-fonts
>Method of using fonts defined as SVG shapes. Removed from SVG 2.0 and considered as a deprecated feature with support being removed from browsers.

**Comment by DigTK** [comment]
Does that mean there's no solution for this problem and we'll have to switch fonts?

**Comment by DigTK** [comment]
(also this explains why I couldn't get it to work during hacknight, now I don't feel so bad)

**Comment by agarzola** [comment]
Switch fonts or, just wait for Chrome to fix that shit. ¯\_(ツ)_/¯

**Comment by DigTK** [comment]
image

**Comment by agarzola** [comment]
☠️

**Pull request closed without merging**
