### PR TITLE
add folding at home announcement

### PR DESCRIPTION
**Pull request by samlachance**
Hello friends,

This PR adds an announcement to the front page of the site that tells users how they can get involved with out F@H team. This PR also adds a newline at the end of the file (courtesy of my text editor).

This PR is marked WIP because rubygems appears to be down so I cannot test it. For whatever reason, I deleted my local repo since my last PR. If anyone would like to pull this and test for yourself then that's fine. Otherwise, I'll wait until rubygems is back up before I remove the WIP

### CODE REVIEW

**Comment by brb3** [comment]
This is a fantastic idea. Thank you for your courage @samlachance .

**Comment by samlachance** [comment]
:+1: Ah also, forgot to mention this. I was going to utilize F@H's API but then I remembered that this is a static site and, as a result, it'd be doing an API call on every request of the front page. I feel like that's not great but if you guys have other thoughts I'm happy to talk about them. 

I think it'd be great to have a 'score board' however without a backend I'm not so sure how to do that in a not-sucky way

**Comment by brb3** [comment]
We'd have to do it with JavaScript, so I don't think there is a not-sucky way :stuck_out_tongue:

**Comment by samlachance** [comment]
Pushed another commit that includes an updated hover color for a button. Viewed in staging and it looks good to me. Removing WIP.

**Pull request merged**
