### PR TITLE
[WIP] Homepage quilt

### PR DESCRIPTION
**Pull request by agarzola**
This PR begins implementation of a JS-powered quilt-like layout of our members’ profile pictures. It currently grabs all of our members, but I’d like for this to be opt-in. So my plan is to have this PR available with a netlify deployment ready to be previewed so it’s easy to communicate to our members what the homepage quilt looks like. Once we‘ve got enough members who’ve opted in, we can make the switch on `_pages/quilt.html` to use only those members.

Should not be merged until the following is done:
- [x] Change the logic in `_pages/quilt.html` to use only members with `members-quilt: true`
- [x] Point each member’s picture to their permalink on the `/members` page (e.g. `/members#username`

### CODE REVIEW

**Comment by agarzola** [comment]
I rebased this branch on latest `master`.

**Comment by agarzola** [comment]
This is blocked until we get at least 30 member profiles. I believe we need another four users to meet this goal.

**Comment by StrangeWill** [comment]
Does `members-quilt` default to true or false? We only got like 11 configured to true (none false).

**Comment by agarzola** [comment]
We default to `false`. This branch is behind master. I believe everyone on master is set to `true`. I’ll rebase this branch in a moment.

**Comment by agarzola** [comment]
So I was wrong. Not all members have `members-quilt` set to `true`. I’ll reach out to those members.

**Comment by StrangeWill** [comment]
Where are we on this with the new additions?

**Comment by agarzola** [comment]
@StrangeWill Soon as #155 is merged, this is unblocked.

**Pull request merged**
