### PR TITLE
Add minor changes to CoC

### PR DESCRIPTION
**Pull request by StrangeWill**
We'll discuss this prior to accepting this and I'll continue making changes.

* I don't like that administrators never "work alone", if no admin is online and something is violating policy, I'm removing it. Additionally I don't like the idea that if a decision is made, that we've already come to a consensus.
* Channel removal for dead/inactive channels (totally earmarked this).

Any other ideas?

### CODE REVIEW

**Comment by brb3** [comment]
I'm fine with both of these. It would be nice if there was some kind of in-between for the first point, though.

I don't want people thinking an admin is going to go rogue, but at the same time, I don't want them thinking shit only happens after we've all had a pow-wow. so... I'm fine with just pulling that language out.

**Comment by StrangeWill** [comment]
I would like to make moderation logs a for-sure thing, I just need to come up with the way we're going to log them, hopefully something easy, I dunno maybe just a google doc? I dunno...

Maybe also push the point that any administrator action is able to be challenged and the process to do so.

**Comment by brb3** [comment]
> Maybe also push the point that any administrator action is able to be challenged and the process to do so.
👍

**Comment by agarzola** [comment]
After in-person discussion, I’m OK with these changes.

**Pull request merged**
